### ISSUE TITLE
Input not working

### ISSUE THREAD

**Issue by Anpert70** [wiredopposite/OGX-Mini#22]
Hi!
So I've been trying to make this work with a PowerA Controller. The problem is that when connected, the led on the pico turns on, but when I try pressing any button it gives no response.

**Comment by wiredopposite** [comment]
Hi, I need some more info, what console is the PowerA controller meant for and which model is it?

**Comment by Anpert70** [comment]
It is a Switch wired controller, and the model is 1521474-01

**Comment by wiredopposite** [comment]
Okay I'll take a look tomorrow and see if I can reproduce the issue. Is it still a problem if you use an earlier version of the firmware?

**Comment by Anpert70** [comment]
Thanks! And yeah, I've tried with older releases but it still isn't working.

**Comment by wiredopposite** [comment]
Not sure why I blanked on this, but it's probably because I don't have that device's VID and PID included in the firmware. Can you plug it into a PC and post those? You can get them in Windows from Device Manager, right click the device (should be under human interface devices), select properties > details tab > hardware ids from the drop down. It'll look like this: HID\VID_046D&PID_C05A

**Comment by Anpert70** [comment]
Sure! USB\VID_20D6&PID_A713

**Comment by Invictaz** [comment]
@wiredopposite is it as simple as just adding PID and VID and recompiling or do we need more to add controller support?

If it is simple I might add some and do a pull request.

**Comment by Anpert70** [comment]
Yup, tried it and it works now! Thanks!
